export const recruitmentDashboardMock = {
  open_job_openings: 6,
  applications_received: 48,
  shortlisted_candidates: 18,
  interviews_scheduled: 9,
  selected_candidates: 5,
  offers_sent: 4,
  offers_accepted: 3,
  employees_joined: 2,
};

export const recruitmentPipelineMock = {
  applications: 48,
  shortlisted: 18,
  interviews: 9,
  selected: 5,
  offers: 4,
  accepted: 3,
  joined: 2,
};

export const jobOpeningsMock = [
  {
    id: 1,
    job_title: "Frontend Developer",
    department_name: "Engineering",
    designation_name: "Software Engineer",
    num_vacancies: 2,
    employment_type: "Full-time",
    location: "Hyderabad",
    status: "Open",
  },
  {
    id: 2,
    job_title: "Backend Developer",
    department_name: "Engineering",
    designation_name: "Software Engineer",
    num_vacancies: 3,
    employment_type: "Full-time",
    location: "Hyderabad",
    status: "Open",
  },
  {
    id: 3,
    job_title: "HR Executive",
    department_name: "Human Resources",
    designation_name: "HR Executive",
    num_vacancies: 1,
    employment_type: "Full-time",
    location: "Bhimavaram",
    status: "Open",
  },
];

export const applicationsMock = [
  {
    id: 1,
    applicant_name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "9876543210",
    current_company: "ABC Technologies",
    experience_years: 2,
    current_salary: 450000,
    expected_salary: 650000,
    notice_period_days: 30,
    source: "LinkedIn",
    status: "Shortlisted",
    applied_at: "2026-09-10",
  },
  {
    id: 2,
    applicant_name: "Priya Reddy",
    email: "priya.reddy@example.com",
    phone: "9876543211",
    current_company: "XYZ Solutions",
    experience_years: 3,
    current_salary: 550000,
    expected_salary: 750000,
    notice_period_days: 60,
    source: "Naukri",
    status: "Applied",
    applied_at: "2026-09-12",
  },
  {
    id: 3,
    applicant_name: "Arjun Kumar",
    email: "arjun.kumar@example.com",
    phone: "9876543212",
    current_company: "Tech Systems",
    experience_years: 4,
    current_salary: 700000,
    expected_salary: 900000,
    notice_period_days: 30,
    source: "Employee Referral",
    status: "Hold",
    applied_at: "2026-09-14",
  },
  {
    id: 4,
    applicant_name: "Sneha Patel",
    email: "sneha.patel@example.com",
    phone: "9876543213",
    current_company: "Digital Labs",
    experience_years: 2,
    current_salary: 400000,
    expected_salary: 600000,
    notice_period_days: 15,
    source: "Company Career Portal",
    status: "Rejected",
    applied_at: "2026-09-15",
  },
];

export const interviewsMock = [
  {
    id: 1,
    applicant_name: "Rahul Sharma",
    job_title: "Frontend Developer",
    interview_round: "Round 1",
    interview_type: "Technical",
    interview_date: "2026-09-25",
    interview_time: "10:00",
    interviewer_name: "Vijay Kumar",
    status: "Scheduled",
  },
  {
    id: 2,
    applicant_name: "Priya Reddy",
    job_title: "Backend Developer",
    interview_round: "Round 2",
    interview_type: "Technical",
    interview_date: "2026-09-26",
    interview_time: "11:30",
    interviewer_name: "Suresh Kumar",
    status: "Scheduled",
  },
  {
    id: 3,
    applicant_name: "Arjun Kumar",
    job_title: "Frontend Developer",
    interview_round: "Final",
    interview_type: "HR",
    interview_date: "2026-09-27",
    interview_time: "15:00",
    interviewer_name: "HR Team",
    status: "Completed",
  },
];

export const offersMock = [
  {
    id: 1,
    applicant_name: "Rahul Sharma",
    position: "Frontend Developer",
    salary: 650000,
    joining_date: "2026-10-15",
    location: "Hyderabad",
    employment_type: "Full-time",
    validity: "2026-10-05",
    status: "Pending",
  },
  {
    id: 2,
    applicant_name: "Priya Reddy",
    position: "Backend Developer",
    salary: 750000,
    joining_date: "2026-10-20",
    location: "Hyderabad",
    employment_type: "Full-time",
    validity: "2026-10-10",
    status: "Accepted",
  },
  {
    id: 3,
    applicant_name: "Arjun Kumar",
    position: "Frontend Developer",
    salary: 850000,
    joining_date: "2026-10-10",
    location: "Hyderabad",
    employment_type: "Full-time",
    validity: "2026-10-01",
    status: "Rejected",
  },
];

export const onboardingMock = [
  {
    id: 1,
    applicant_name: "Priya Reddy",
    email: "priya.reddy@example.com",
    phone: "9876543211",
    experience_years: 3,
    joining_date: "2026-10-20",
    status: "Offer Accepted",
    progress: "Documents Pending",
  },
  {
    id: 2,
    applicant_name: "Kiran Rao",
    email: "kiran.rao@example.com",
    phone: "9876543214",
    experience_years: 2,
    joining_date: "2026-10-12",
    status: "Offer Accepted",
    progress: "Ready for Joining",
  },
];