import React from "react";
import "./ReportsTable.css";

const reports = [
  {
    name: "Employee Summary Report",
    description: "Complete overview of all employees",
    category: "Employee",
    type: "Summary",
    date: "15 May 2024",
    time: "10:30 AM",
    format: "PDF",
  },
  {
    name: "Attendance Report",
    description: "Monthly attendance summary",
    category: "Attendance",
    type: "Detailed",
    date: "15 May 2024",
    time: "09:15 AM",
    format: "Excel",
  },
  {
    name: "Leave Report",
    description: "Leave utilization and balance",
    category: "Leave",
    type: "Summary",
    date: "14 May 2024",
    time: "04:45 PM",
    format: "PDF",
  },
  {
    name: "Payroll Summary",
    description: "Monthly payroll summary report",
    category: "Payroll",
    type: "Summary",
    date: "14 May 2024",
    time: "02:30 PM",
    format: "Excel",
  },
  {
    name: "Department Report",
    description: "Department wise statistics",
    category: "Department",
    type: "Summary",
    date: "13 May 2024",
    time: "11:20 AM",
    format: "PDF",
  },
  {
    name: "Performance Report",
    description: "Employee performance analytics",
    category: "Performance",
    type: "Analytics",
    date: "13 May 2024",
    time: "10:00 AM",
    format: "Excel",
  },
  {
    name: "Training Report",
    description: "Training completion and status",
    category: "Training",
    type: "Detailed",
    date: "12 May 2024",
    time: "03:15 PM",
    format: "PDF",
  },
  {
    name: "Overtime Report",
    description: "Overtime hours and costs",
    category: "Attendance",
    type: "Detailed",
    date: "12 May 2024",
    time: "01:45 PM",
    format: "Excel",
  },
];

const ReportsTable = () => {
  return (
    <div className="reports-table-container">

      {/* Filters */}
      <div className="reports-filters">
        <div className="filter-group">
          <label>Report Category</label>
          <select>
            <option>All Categories</option>
            <option>Employee</option>
            <option>Attendance</option>
            <option>Leave</option>
            <option>Payroll</option>
          </select>
        </div>

        <div className="filter-group">
          <label>Report Type</label>
          <select>
            <option>All Types</option>
            <option>Summary</option>
            <option>Detailed</option>
            <option>Analytics</option>
          </select>
        </div>

        <div className="filter-group date-filter">
          <label>Date Range</label>
          <input type="text" value="01 May 2024 - 15 May 2024" readOnly />
        </div>

        <button className="apply-btn">Apply Filters</button>
        <button className="reset-btn">Reset</button>
      </div>

      {/* Table */}
      <div className="reports-table-wrapper">
        <table className="reports-table">
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Category</th>
              <th>Report Type</th>
              <th>Generated By</th>
              <th>Generated On</th>
              <th>Format</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            {reports.map((report, index) => (
              <tr key={index}>
                <td>
                  <div className="report-name">
                    <div className="row-icon">▤</div>

                    <div>
                      <strong>{report.name}</strong>
                      <small>{report.description}</small>
                    </div>
                  </div>
                </td>

                <td>
                  <span className={`category ${report.category.toLowerCase()}`}>
                    {report.category}
                  </span>
                </td>

                <td>{report.type}</td>

                <td>Admin User</td>

                <td>
                  <div className="generated-date">
                    <strong>{report.date}</strong>
                    <span>{report.time}</span>
                  </div>
                </td>

                <td>
                  <span className={`format ${report.format.toLowerCase()}`}>
                    {report.format}
                  </span>
                </td>

                <td>
                  <div className="table-actions">
                    <button className="view-btn">◉</button>
                    <button className="download-btn">↓</button>
                    <button className="mail-btn">✉</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Bottom */}
      <div className="reports-footer">
        <span>Showing 1 to 8 of 32 entries</span>

        <div className="pagination">
          <button>‹</button>
          <button className="active">1</button>
          <button>2</button>
          <button>3</button>
          <button>4</button>
          <button>›</button>
        </div>
      </div>
    </div>
  );
};

export default ReportsTable;